#!/bin/bash

DIR=$( cd "$( dirname `readlink -f "${BASH_SOURCE[0]}"` )" &> /dev/null && pwd )
HOOK="$DIR/../../.git/hooks/pre-commit"

[[ ! -e "$HOOK" ]] && ln -s "$DIR/pre-commit" "$HOOK"
git apply --cached "$DIR/debug.patch" -R --recount &> /dev/null || true
