name: Cpp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup system dependencies
      run: |
        sudo apt-get -y install cppcheck
    - name: Run cppcheck
      run: |
        ./misc/travis/cppcheck.sh
